# Generated by Django 5.2.10 on 2026-01-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_monthlybudget_categorybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='monthly_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='expenses.monthlybudget'),
        ),
    ]
